### ISSUE TITLE
Move to XRootD as primary data source

### ISSUE THREAD

**Issue by wdconinc** [eic/firehose#7]
**Is your feature request related to a problem? Please describe.**
We are using S3 access to the minio appliance to spider the directories. Those are secondary copies of direct writes to XRootD, so it is only a matter of time before we run into synchronization issues, or we just stop updating S3 entirely on a regular basis. Also, S3 is slow and the minio container is constrained.

**Describe the solution you'd like**
We could use an XRootD container to do the same thing, presumably it has the XrdPosix preload or xrdfs. Currently maintained by OSG at https://hub.docker.com/layers/opensciencegrid/xrootd-standalone/3.6-release/images/sha256-9cf2eba5e6bd6239a5b484e2849d5de8418cf1d336dac8a701e673fe9e5fb3a9?context=explore or the newer https://hub.docker.com/layers/opensciencegrid/xrootd-standalone/23-release/images/sha256-e033e5d541f03bc7b9d58b4743316d890ca74dcb45e45a918e1ff4a40ac93697?context=explore

There may also be other XRootD containers on Docker Hub, or even better on ghcr.io for faster access here.

**Comment by wdconinc** [comment]
Slightly smaller and future proof on account of rucio: https://hub.docker.com/r/rucio/xrootd/tags

**Comment by wdconinc** [comment]
But there is no way to get time-sorted infromation from xrootd except by using the posix preload, and that would be more expensive than S3, so for now there is probably not a good reason to move over.

**Comment by wdconinc** [comment]
@rahmans1 Do we need to bump this up in priority now that there is no primary writing to S3?

**Comment by rahmans1** [comment]
Can we close this issue now? @wdconinc
